# Generated by Django 6.0.4 on 2026-05-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='email_subject',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='alert',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broadcastmention',
            name='broadcast_type',
            field=models.CharField(choices=[('RADIO', 'Radio'), ('TV', 'TV'), ('PODCAST', 'Podcast'), ('ONLINE', 'Online')], default='RADIO', max_length=20),
        ),
        migrations.AddField(
            model_name='onlinearticle',
            name='relevancy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='relevancy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='alert',
            name='frequency',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20),
        ),
    ]
