# Generated by Django 6.0.4 on 2026-05-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alert_email_subject_alert_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='organization',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='organization',
            name='gradient_color1',
            field=models.CharField(default='#1d4ed8', max_length=7),
        ),
        migrations.AddField(
            model_name='organization',
            name='gradient_color2',
            field=models.CharField(default='#0f172a', max_length=7),
        ),
        migrations.AddField(
            model_name='organization',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='organization',
            name='x_handle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
