# Generated by Django 6.0.4 on 2026-05-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_organization_address_organization_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['category', 'keyword']},
        ),
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='keyword',
            name='category',
            field=models.CharField(default='brand', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together={('organization', 'keyword', 'category')},
        ),
    ]
