# Generated by Django 6.0.4 on 2026-05-10 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_alter_keyword_options_alter_keyword_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('online', 'Online'), ('social', 'Social'), ('print', 'Print'), ('broadcast', 'Broadcast')], default='online', max_length=20)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('handle', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('reach', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_sources', to='monitor.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
