# Generated by Django 6.1 on 2026-08-10 14:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_mediasource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastmention',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('mixed', 'Mixed')], default='neutral', max_length=20),
        ),
        migrations.AlterField(
            model_name='onlinearticle',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('mixed', 'Mixed')], default='neutral', max_length=20),
        ),
        migrations.AlterField(
            model_name='printarticle',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('mixed', 'Mixed')], default='neutral', max_length=20),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('mixed', 'Mixed')], default='neutral', max_length=20),
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('report_type', models.CharField(max_length=100)),
                ('modules', models.JSONField(default=list)),
                ('scope', models.JSONField(default=list)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='monitor.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
