# Generated by Django 5.2.14 on 2026-08-12 09:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_alter_broadcastmention_sentiment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='banner_image',
            field=models.FileField(blank=True, null=True, upload_to='alert_banners/'),
        ),
        migrations.AddField(
            model_name='alert',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the digest was last sent (watermark for new records)', null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='recipients',
            field=models.TextField(blank=True, help_text='Comma-separated recipient emails'),
        ),
        migrations.AddField(
            model_name='broadcastmention',
            name='relevancy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='competitor',
            name='aliases',
            field=models.TextField(blank=True, default='', help_text='Comma-separated alternative names/keywords used to match coverage'),
        ),
        migrations.AddField(
            model_name='printarticle',
            name='reach',
            field=models.IntegerField(default=0, help_text='Estimated readership (circulation × readers-per-copy).'),
        ),
        migrations.AddField(
            model_name='printarticle',
            name='relevancy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='organization',
            name='industry',
            field=models.CharField(blank=True, choices=[('Banking & Financial Services', 'Banking & Financial Services'), ('Mining & Metals', 'Mining & Metals'), ('Telecommunications', 'Telecommunications'), ('Retail', 'Retail'), ('Education & Research', 'Education & Research'), ('Healthcare', 'Healthcare'), ('Government', 'Government'), ('Energy', 'Energy'), ('Technology', 'Technology'), ('Marketing', 'Marketing'), ('Cosmetics, Beauty & Personal Care', 'Cosmetics, Beauty & Personal Care'), ('Public Relations', 'Public Relations'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='page_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='platform',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('X', 'X'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('YouTube', 'YouTube'), ('TikTok', 'TikTok'), ('Other', 'Other')], default='Facebook', max_length=50),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('terms', models.JSONField(default=list)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='monitor.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('headline', models.TextField()),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('summary', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('date_published', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('matched_keywords', models.CharField(blank=True, max_length=300)),
                ('sentiment_score', models.FloatField(default=0)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('mixed', 'Mixed')], default='neutral', max_length=20)),
                ('reach', models.IntegerField(default=0)),
                ('cpm', models.FloatField(default=0)),
                ('ave', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('rank', models.FloatField(default=0)),
                ('coverage_type', models.CharField(blank=True, default='Not Set', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='monitor.competitor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_articles', to='monitor.organization')),
            ],
            options={
                'ordering': ['-date_published', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('kind', models.CharField(default='issue', max_length=20)),
                ('issue_query', models.TextField(help_text='The saga/issue the report isolates coverage for.')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('candidate_ids', models.JSONField(default=dict)),
                ('selected_ids', models.JSONField(default=dict)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reports', to='monitor.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_analyses', to='monitor.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('organization', 'date_from', 'date_to')},
            },
        ),
    ]
