# Generated by Django 5.2.14 on 2026-06-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_alter_broadcastmention_sentiment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='aliases',
            field=models.TextField(blank=True, default='', help_text='Comma-separated alternative names/keywords used to match coverage'),
        ),
    ]
