# Generated by Django 5.2.14 on 2026-06-04 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_competitor_aliases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediapost',
            name='platform',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'X'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('YouTube', 'YouTube'), ('TikTok', 'TikTok'), ('Other', 'Other')], default='Facebook', max_length=50),
        ),
        migrations.CreateModel(
            name='CompetitorArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('headline', models.TextField()),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('summary', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('date_published', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('matched_keywords', models.CharField(blank=True, max_length=300)),
                ('sentiment_score', models.FloatField(default=0)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('mixed', 'Mixed')], default='neutral', max_length=20)),
                ('reach', models.IntegerField(default=0)),
                ('cpm', models.FloatField(default=0)),
                ('ave', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('rank', models.FloatField(default=0)),
                ('coverage_type', models.CharField(blank=True, default='Not Set', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='monitor.competitor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_articles', to='monitor.organization')),
            ],
            options={
                'ordering': ['-date_published', '-created_at'],
            },
        ),
    ]
