# Generated by Django 5.2.14 on 2026-06-08 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_alter_socialmediapost_platform_competitorarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_analyses', to='monitor.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('organization', 'date_from', 'date_to')},
            },
        ),
    ]
