# Generated by Django 5.2.14 on 2026-08-20 18:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_event_model_and_alert_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='One line under the package name, e.g. "For small comms teams".', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='0 shows as "Talk to us" instead of a figure.', max_digits=12)),
                ('currency', models.CharField(default='BWP', max_length=8)),
                ('billing_period', models.CharField(choices=[('monthly', 'Per month'), ('quarterly', 'Per quarter'), ('annual', 'Per year')], default='monthly', max_length=20)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_featured', models.BooleanField(default=False, help_text='Highlights this package as the recommended tier.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from the price list without deleting it.')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'price', 'name'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='plan_status',
            field=models.CharField(choices=[('trial', 'Free trial'), ('active', 'Paid subscription'), ('pending', 'Awaiting activation'), ('expired', 'Trial ended')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='monitor.package'),
        ),
        migrations.CreateModel(
            name='SubscriptionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved & activated'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_subscription_requests', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='monitor.organization')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='monitor.package')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
