# Generated by Django 5.2.14 on 2026-06-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_reportanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediapost',
            name='page_name',
            field=models.TextField(blank=True),
        ),
    ]
