# Generated by Django 5.2.14 on 2026-06-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_alter_socialmediapost_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='banner_image',
            field=models.FileField(blank=True, null=True, upload_to='alert_banners/'),
        ),
        migrations.AddField(
            model_name='alert',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the digest was last sent (watermark for new records)', null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='recipients',
            field=models.TextField(blank=True, help_text='Comma-separated recipient emails'),
        ),
    ]
