# Generated by Django 5.2.14 on 2026-08-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_seed_placeholder_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='accent_color',
            field=models.CharField(default='#3891C7', help_text='Colour of the bar across the top of the card.', max_length=7),
        ),
        migrations.AddField(
            model_name='package',
            name='contact_only',
            field=models.BooleanField(default=False, help_text='This tier is arranged with sales rather than picked self-service.'),
        ),
        migrations.AddField(
            model_name='package',
            name='cta_label',
            field=models.CharField(blank=True, help_text='Button text. Defaults to "Start free trial".', max_length=40),
        ),
        migrations.AddField(
            model_name='package',
            name='excluded_features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='package',
            name='exclusion_note',
            field=models.CharField(blank=True, help_text='Small note under each exclusion, e.g. "Enterprise only".', max_length=60),
        ),
        migrations.AddField(
            model_name='package',
            name='eyebrow',
            field=models.CharField(blank=True, help_text='Small label above the name, e.g. "Full scope".', max_length=60),
        ),
        migrations.AddField(
            model_name='package',
            name='highlight_body',
            field=models.CharField(blank=True, help_text='Callout box text.', max_length=300),
        ),
        migrations.AddField(
            model_name='package',
            name='highlight_title',
            field=models.CharField(blank=True, help_text='Callout box heading, e.g. "Only on Enterprise".', max_length=60),
        ),
        migrations.AddField(
            model_name='package',
            name='is_dark',
            field=models.BooleanField(default=False, help_text='Render this card on a dark background.'),
        ),
        migrations.AddField(
            model_name='package',
            name='price_note',
            field=models.CharField(blank=True, help_text='Line under the price, e.g. "Billed annually · $588 per year".', max_length=160),
        ),
        migrations.AddField(
            model_name='package',
            name='price_override',
            field=models.CharField(blank=True, help_text='Shown instead of a figure, e.g. "Custom". Hides the period.', max_length=40),
        ),
        migrations.AlterField(
            model_name='package',
            name='currency',
            field=models.CharField(default='USD', max_length=8),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='package',
            name='tagline',
            field=models.CharField(blank=True, help_text='One line under the package name, e.g. "Growing organisations and agencies".', max_length=200),
        ),
    ]
