# Generated by Django 5.2.14 on 2026-06-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_alert_banner_image_alert_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmention',
            name='relevancy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='printarticle',
            name='relevancy',
            field=models.FloatField(default=0),
        ),
    ]
