# Generated by Django 5.2.14 on 2026-08-23 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_real_price_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('price_display', models.CharField(help_text='Shown as written, e.g. "$2,412.30".', max_length=40)),
                ('change_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(help_text='e.g. "Weekly digest", "Sector report".', max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('blurb', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('published_on', models.DateField()),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', '-published_on'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('heading', models.CharField(blank=True, help_text='Heading above the story list. Defaults to "Top <name> intelligence this week".', max_length=200)),
                ('shows_ticker', models.BooleanField(default=False, help_text='Show the commodities ticker while this sector is selected.')),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SectorStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('source_label', models.CharField(help_text='How the source is credited, e.g. "Regional business press".', max_length=120)),
                ('url', models.URLField(blank=True, help_text='Optional link out to the story.', max_length=2000)),
                ('published_on', models.DateField()),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Rank within the sector. Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='monitor.sector')),
            ],
            options={
                'verbose_name_plural': 'Sector stories',
                'ordering': ['display_order', '-published_on'],
            },
        ),
    ]
