# Generated by Django 5.2.14 on 2026-06-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_broadcastmention_relevancy_printarticle_relevancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediapost',
            name='platform',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('X', 'X'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('YouTube', 'YouTube'), ('TikTok', 'TikTok'), ('Other', 'Other')], default='Facebook', max_length=50),
        ),
    ]
