# Generated by Django 5.2.14 on 2026-06-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_alter_socialmediapost_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='printarticle',
            name='reach',
            field=models.IntegerField(default=0, help_text='Estimated readership (circulation × readers-per-copy).'),
        ),
    ]
