# Generated by Django 5.2.14 on 2026-07-13 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_printarticle_reach'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('issue_query', models.TextField(help_text='The saga/issue the report isolates coverage for.')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('candidate_ids', models.JSONField(default=dict)),
                ('selected_ids', models.JSONField(default=dict)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reports', to='monitor.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
