# Generated by Django 5.2.14 on 2026-08-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_seed_sectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='entitlements',
            field=models.JSONField(blank=True, default=list, help_text='Feature codes this package grants, e.g. ["report_download", "premium_reports"]. The Entitlements section of this page lists every available code.'),
        ),
        migrations.AddField(
            model_name='package',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Show on the published price list. Untick for a tier that is assignable (onboarding, admin) but not advertised — the Free tier, for example.'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to retire the tier without deleting it. Inactive tiers cannot be chosen or assigned.'),
        ),
    ]
