# Generated by Django 5.2.14 on 2026-08-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_seed_sectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodityquote',
            name='is_ai_generated',
            field=models.BooleanField(default=False, help_text='Refreshed daily by the sector-intelligence job, not an editor.'),
        ),
        migrations.AddField(
            model_name='sectorstory',
            name='is_ai_generated',
            field=models.BooleanField(default=False, help_text='Written by the daily sector-intelligence job, not an editor.'),
        ),
    ]
