# Generated by Django 5.2.14 on 2026-08-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0016_issuereport_kind_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmention',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='competitorarticle',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='onlinearticle',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='printarticle',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='industry',
            field=models.CharField(blank=True, choices=[('Banking & Financial Services', 'Banking & Financial Services'), ('Mining & Metals', 'Mining & Metals'), ('Telecommunications', 'Telecommunications'), ('Retail', 'Retail'), ('Education & Research', 'Education & Research'), ('Healthcare', 'Healthcare'), ('Government', 'Government'), ('Energy', 'Energy'), ('Technology', 'Technology'), ('Marketing', 'Marketing'), ('Cosmetics, Beauty & Personal Care', 'Cosmetics, Beauty & Personal Care'), ('Public Relations', 'Public Relations'), ('Other', 'Other')], max_length=100),
        ),
    ]
