# Generated by Django 5.2.14 on 2026-08-27 07:00

import django.db.models.deletion
import django.utils.timezone
import monitor.onboarding_models
import monitor.payment_models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0016_package_entitlement_map_and_free_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='AgencyDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('individual', 'Individual user'), ('organisation', 'Representing an organisation or agency')], default='individual', max_length=20)),
                ('organisation_name', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(blank=True, help_text="The user's position or title within the organisation.", max_length=150)),
                ('organisation_email', models.EmailField(blank=True, help_text='Official organisation address, where different from the account address.', max_length=254)),
                ('organisation_phone', models.CharField(blank=True, max_length=50)),
                ('registration_number', models.CharField(blank=True, help_text='Company or entity registration number, if provided.', max_length=100)),
                ('is_authorised_representative', models.BooleanField(default=False, help_text='The user explicitly confirmed they are authorised to act for the organisation.')),
                ('authorised_at', models.DateTimeField(blank=True, null=True)),
                ('authorisation_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('not_required', 'No further verification required'), ('pending', 'Awaiting verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_required', max_length=20)),
                ('supporting_document', models.FileField(blank=True, help_text='Optional. Not required by the current onboarding rules.', null=True, upload_to='agency_declarations/')),
                ('verification_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_declarations', to='monitor.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agency_declaration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('email', models.EmailField(help_text='The address this token was issued for.', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=monitor.onboarding_models._default_verification_expiry)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('terms', 'Terms & Conditions'), ('privacy', 'Privacy & Personal Data Consent'), ('disclaimer', 'Disclaimer')], max_length=30)),
                ('version', models.CharField(help_text='e.g. "1.0", "1.1". Sorted by effective date, not by this string.', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, help_text='Short plain-language explanation shown above the document — why this is being asked for and what it covers.')),
                ('body', models.TextField(help_text='The document itself. Blank lines separate paragraphs.')),
                ('consent_label', models.CharField(help_text='The wording next to the tick box, e.g. "I have read and accept the Terms & Conditions".', max_length=300)),
                ('jurisdiction', models.CharField(default='Botswana', help_text='The law this version is drafted for review under.', max_length=100)),
                ('review_status', models.CharField(choices=[('draft', 'Draft — not yet reviewed'), ('in_review', 'With legal for review'), ('approved', 'Approved by legal counsel')], default='draft', max_length=20)),
                ('review_note', models.TextField(blank=True, help_text='Internal note for whoever owns legal review — what still needs checking.')),
                ('requires_acceptance', models.BooleanField(default=True, help_text='Untick for a document that is published for reference but not blocking onboarding.')),
                ('is_published', models.BooleanField(default=False, help_text='Only published versions are ever shown to a user or accepted.')),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['doc_type', '-effective_from', '-version'],
                'unique_together': {('doc_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('registered', 'Registered'), ('email_verified', 'Email verified'), ('profile_completed', 'Profile completed'), ('agency_declared', 'Agency declared'), ('terms_accepted', 'Terms accepted'), ('privacy_accepted', 'Privacy consent given'), ('disclaimer_accepted', 'Disclaimer accepted'), ('payment_method_added', 'Payment method added'), ('plan_assigned', 'Plan assigned'), ('complete', 'Onboarding complete')], default='registered', max_length=30)),
                ('history', models.JSONField(blank=True, default=dict, help_text='{state: ISO timestamp} — when each state was first reached.')),
                ('is_legacy', models.BooleanField(default=False, help_text='Account predates onboarding and was marked complete on migration.')),
                ('payment_skipped', models.BooleanField(default=False, help_text='The payment step was skipped because no payment gateway was enabled.')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Onboarding progress',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(help_text='Which payment provider issued the token.', max_length=40)),
                ('provider_customer_id', models.CharField(blank=True, max_length=200)),
                ('provider_token', models.CharField(help_text="The provider's token for the stored card. Never a card number.", max_length=200)),
                ('brand', models.CharField(blank=True, help_text='e.g. "visa", "mastercard".', max_length=40)),
                ('last4', models.CharField(blank=True, max_length=4)),
                ('exp_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('exp_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('holder_name', models.CharField(blank=True, max_length=200)),
                ('is_default', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_methods_added', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='monitor.organization')),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('terms', 'Terms & Conditions'), ('privacy', 'Privacy & Personal Data Consent'), ('disclaimer', 'Disclaimer')], max_length=30)),
                ('version', models.CharField(max_length=20)),
                ('decision', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='accepted', max_length=20)),
                ('source', models.CharField(choices=[('onboarding', 'Onboarding'), ('reconsent', 'Re-consent to a new version'), ('settings', 'Account settings'), ('admin', 'Recorded by an administrator')], default='onboarding', max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('organization', models.ForeignKey(blank=True, help_text='The organisation the user was acting for at the time.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_records', to='monitor.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='monitor.legaldocument')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['user', 'doc_type', '-occurred_at'], name='monitor_con_user_id_d0312d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('provider_reference', models.CharField(blank=True, help_text="The provider's own id for this charge.", max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=300)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('settlement_hold_days', models.PositiveSmallIntegerField(default=monitor.payment_models.settlement_hold_days, help_text='The holding period applied to this payment, captured at the time it was taken so a later change to the configured default does not rewrite history.')),
                ('settlement_available_at', models.DateTimeField(blank=True, help_text='When OUR holding period elapses. The payment provider’s own settlement timetable is separate and is not controlled by this application.', null=True)),
                ('provider_settlement_at', models.DateTimeField(blank=True, help_text='When the provider reports the funds will actually be, or were, released.', null=True)),
                ('settled_at', models.DateTimeField(blank=True, help_text='When the funds were actually extracted.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='monitor.organization')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='monitor.package')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='monitor.paymentmethod')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='monitor_pay_organiz_76e688_idx')],
            },
        ),
    ]
