# Generated by Django 5.2.14 on 2026-08-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0017_broadcastmention_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printarticle',
            name='cover_image',
            field=models.FileField(blank=True, help_text='Front-page scan/cover image, when captured via automated OCR ingestion.', null=True, upload_to='print_covers/'),
        ),
    ]
