# Generated by Django 5.2.14 on 2026-08-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_seed_sectors'),
        ('monitor', '0018_printarticle_cover_image'),
    ]

    operations = [
    ]
