# Generated by Django 5.2.14 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0015_commodityquote_is_ai_generated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediapost',
            name='platform',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('X', 'X'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('YouTube', 'YouTube'), ('TikTok', 'TikTok'), ('Facebook Group', 'Facebook Group'), ('Other', 'Other')], default='Facebook', max_length=50),
        ),
    ]
