# Generated by Django 5.2.14 on 2026-08-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0019_merge_0014_seed_sectors_0018_printarticle_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorarticle',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
