# Generated by Django 5.2.14 on 2026-08-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0019_socialmediapost_facebook_group_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmention',
            name='sentiment_rationale',
            field=models.TextField(blank=True, default='', help_text='Why an AI sentiment pass set this — see monitor/sentiment_ai.py. Blank when sentiment was set manually, by a vendor feed, or not yet analysed.'),
        ),
        migrations.AddField(
            model_name='competitorarticle',
            name='sentiment_rationale',
            field=models.TextField(blank=True, default='', help_text='Why an AI sentiment pass set this — see monitor/sentiment_ai.py. Blank when sentiment was set manually, by a vendor feed, or not yet analysed.'),
        ),
        migrations.AddField(
            model_name='onlinearticle',
            name='sentiment_rationale',
            field=models.TextField(blank=True, default='', help_text='Why an AI sentiment pass set this — see monitor/sentiment_ai.py. Blank when sentiment was set manually, by a vendor feed, or not yet analysed.'),
        ),
        migrations.AddField(
            model_name='printarticle',
            name='sentiment_rationale',
            field=models.TextField(blank=True, default='', help_text='Why an AI sentiment pass set this — see monitor/sentiment_ai.py. Blank when sentiment was set manually, by a vendor feed, or not yet analysed.'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='sentiment_rationale',
            field=models.TextField(blank=True, default='', help_text='Why an AI sentiment pass set this — see monitor/sentiment_ai.py. Blank when sentiment was set manually, by a vendor feed, or not yet analysed.'),
        ),
    ]
