# Generated by Django 5.2.14 on 2026-08-28 11:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0019_seed_legal_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=200)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('answers', models.JSONField(default=dict)),
                ('note', models.TextField(blank=True)),
                ('score', models.PositiveSmallIntegerField(default=0, help_text='Percentage, 0–100.')),
                ('tier', models.CharField(blank=True, choices=[('strong', 'Strong'), ('growing', 'Growing'), ('attention', 'Needs attention')], max_length=20)),
                ('fit', models.CharField(blank=True, choices=[('high_value', 'High-priority fit'), ('eligible', 'Good fit'), ('early', 'Early stage')], max_length=20)),
                ('urgency', models.CharField(blank=True, max_length=20)),
                ('budget', models.CharField(blank=True, max_length=20)),
                ('timeline', models.CharField(blank=True, max_length=20)),
                ('platforms', models.JSONField(default=list)),
                ('requested_action', models.CharField(blank=True, choices=[('call', 'Discovery call'), ('webinar', 'Strategy session'), ('guide', 'Foundation guide')], max_length=20)),
                ('requested_action_at', models.DateTimeField(blank=True, null=True)),
                ('report_sent_at', models.DateTimeField(blank=True, null=True)),
                ('sales_notified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='monitor_ass_created_4f6cbe_idx'), models.Index(fields=['fit', '-created_at'], name='monitor_ass_fit_5f1fec_idx')],
            },
        ),
    ]
