# Generated by Django 5.2.14 on 2026-08-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0020_broadcastmention_sentiment_rationale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='sentiment_subject',
            field=models.CharField(blank=True, default='', help_text="Who coverage is actually ABOUT, if different from this org's own name — e.g. an agency ('Launch Comms') tracking coverage of its client ('Botswana Power Corporation'). The AI sentiment pass (monitor/sentiment_ai.py) reasons from this entity's perspective when set; falls back to `name` when blank. Leave blank for an org that IS the brand being covered.", max_length=200),
        ),
    ]
