# Generated by Django 5.2.14 on 2026-08-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0021_refund_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentrecord',
            name='doc_type',
            field=models.CharField(choices=[('terms', 'Terms & Conditions'), ('privacy', 'Privacy & Personal Data Consent'), ('disclaimer', 'Disclaimer'), ('refund', 'Refund & Cancellation Policy')], max_length=30),
        ),
    ]
