# Generated by Django 5.2.14 on 2026-09-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0021_organization_sentiment_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediapost',
            name='date_correction_note',
            field=models.TextField(blank=True, default='', help_text="Evidence an AI date-extraction pass used to change date_published away from its ingestion-time value — see monitor/date_ai.py's extract_published_date(). Blank when date_published has never been AI-corrected (either it was already right, or no correction was attempted/found)."),
        ),
    ]
