# Generated by Django 5.2.14 on 2026-09-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0022_alter_consentrecord_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='current_period_end',
            field=models.DateTimeField(blank=True, help_text='When the paid period runs out. Access stops here unless a renewal extends it. Left blank for a subscription activated by hand with no agreed end date, which never lapses on its own.', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='plan_status',
            field=models.CharField(choices=[('trial', 'Free trial'), ('active', 'Paid subscription'), ('pending', 'Awaiting activation'), ('expired', 'Trial ended'), ('past_due', 'Payment overdue')], default='active', max_length=20),
        ),
    ]
