# Generated by Django 5.2.14 on 2026-09-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0023_organization_current_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsubmission',
            name='channel',
            field=models.CharField(blank=True, db_index=True, help_text='Where the visit came from: meta, google, linkedin, direct, referral…', max_length=50),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='click_id',
            field=models.CharField(blank=True, help_text='The ad platform’s own click identifier (fbclid, gclid…), when present.', max_length=200),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='landing_path',
            field=models.CharField(blank=True, help_text='The first page of the visit, which is not always the assessment.', max_length=200),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='referrer',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='utm_campaign',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='utm_content',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='utm_source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='utm_term',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='assessmentsubmission',
            index=models.Index(fields=['channel', '-created_at'], name='monitor_ass_channel_d9ecec_idx'),
        ),
    ]
