# Generated by Django 5.2.14 on 2026-09-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0026_visitcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingprogress',
            name='skip_trial_requested',
            field=models.BooleanField(default=False, help_text='Chose "skip trial, pay now" at signup rather than "start free trial". Surfaced at the plan step to emphasise paying immediately over the usual request-an-invoice-and-stay-on-trial path; does not skip any other step.'),
        ),
    ]
