# Generated by Django 5.2.14 on 2026-09-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0034_cookie_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('channel', models.CharField(db_index=True, max_length=50)),
                ('utm_source', models.CharField(blank=True, max_length=200)),
                ('utm_medium', models.CharField(blank=True, max_length=200)),
                ('utm_campaign', models.CharField(blank=True, max_length=200)),
                ('landing_path', models.CharField(blank=True, max_length=200)),
                ('visits', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'visit count',
                'verbose_name_plural': 'visit counts',
                'ordering': ['-date', '-visits'],
                'indexes': [models.Index(fields=['-date', 'channel'], name='monitor_vis_date_5254a1_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'channel', 'utm_source', 'utm_medium', 'utm_campaign', 'landing_path'), name='unique_visit_bucket')],
            },
        ),
    ]
