# Generated by Django 5.2.14 on 2026-09-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0035_visitcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmention',
            name='relevancy_ai_rationale',
            field=models.TextField(blank=True, default='', help_text='Why an AI disambiguation pass set relevancy_ai_relevant — see monitor/relevancy_ai.py. Blank when not yet checked.'),
        ),
        migrations.AddField(
            model_name='broadcastmention',
            name='relevancy_ai_relevant',
            field=models.BooleanField(blank=True, default=None, help_text="Whether an AI disambiguation pass (see monitor/relevancy_ai.py) confirmed this keyword/competitor match is genuinely about this organisation, as opposed to an unrelated entity that happens to share the same tracked term (e.g. 'BPC' the peptide vs. Botswana Power Corporation). NULL when not yet checked — relevancy (the deterministic keyword score) alone still governs visibility until then. False permanently excludes the row from filter_relevant() regardless of score.", null=True),
        ),
        migrations.AddField(
            model_name='onlinearticle',
            name='relevancy_ai_rationale',
            field=models.TextField(blank=True, default='', help_text='Why an AI disambiguation pass set relevancy_ai_relevant — see monitor/relevancy_ai.py. Blank when not yet checked.'),
        ),
        migrations.AddField(
            model_name='onlinearticle',
            name='relevancy_ai_relevant',
            field=models.BooleanField(blank=True, default=None, help_text="Whether an AI disambiguation pass (see monitor/relevancy_ai.py) confirmed this keyword/competitor match is genuinely about this organisation, as opposed to an unrelated entity that happens to share the same tracked term (e.g. 'BPC' the peptide vs. Botswana Power Corporation). NULL when not yet checked — relevancy (the deterministic keyword score) alone still governs visibility until then. False permanently excludes the row from filter_relevant() regardless of score.", null=True),
        ),
        migrations.AddField(
            model_name='printarticle',
            name='relevancy_ai_rationale',
            field=models.TextField(blank=True, default='', help_text='Why an AI disambiguation pass set relevancy_ai_relevant — see monitor/relevancy_ai.py. Blank when not yet checked.'),
        ),
        migrations.AddField(
            model_name='printarticle',
            name='relevancy_ai_relevant',
            field=models.BooleanField(blank=True, default=None, help_text="Whether an AI disambiguation pass (see monitor/relevancy_ai.py) confirmed this keyword/competitor match is genuinely about this organisation, as opposed to an unrelated entity that happens to share the same tracked term (e.g. 'BPC' the peptide vs. Botswana Power Corporation). NULL when not yet checked — relevancy (the deterministic keyword score) alone still governs visibility until then. False permanently excludes the row from filter_relevant() regardless of score.", null=True),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='relevancy_ai_rationale',
            field=models.TextField(blank=True, default='', help_text='Why an AI disambiguation pass set relevancy_ai_relevant — see monitor/relevancy_ai.py. Blank when not yet checked.'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='relevancy_ai_relevant',
            field=models.BooleanField(blank=True, default=None, help_text="Whether an AI disambiguation pass (see monitor/relevancy_ai.py) confirmed this keyword/competitor match is genuinely about this organisation, as opposed to an unrelated entity that happens to share the same tracked term (e.g. 'BPC' the peptide vs. Botswana Power Corporation). NULL when not yet checked — relevancy (the deterministic keyword score) alone still governs visibility until then. False permanently excludes the row from filter_relevant() regardless of score.", null=True),
        ),
    ]
