# Generated by Django 5.2.14 on 2026-09-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0036_relevancy_ai_disambiguation'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='is_acronym',
            field=models.BooleanField(default=False, help_text="Bare acronym/short-form term (e.g. 'EFF') prone to false-positive collisions with unrelated entities or slang sharing the same letters. media-monitor's crawler runs a synchronous AI disambiguation check (fetcher/relevancy_ai.py) before pushing a match that ONLY matched via acronym-flagged term(s), rather than waiting for the scheduled post-hoc relevancy_ai pass (see monitor/relevancy_ai.py) to catch it later."),
        ),
    ]
