server {
    listen 80;
    client_max_body_size 50M;  

    location /static/ {
    alias /app/staticfiles/;
    }

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # Allow long-running requests (e.g. AI report generation) to complete.
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
    }
}

server {
    listen 80;
    client_max_body_size 50M;
    server_name extractor.sociallight.africa;
    location /static/ {
     alias /app/static/;      # 👈 changed from /app/staticfiles/
   }
 
    location / {
        proxy_pass http://extractor:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
